name: Publish

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    defaults:
      run:
        working-directory: YuKitsune.Configuration.Env

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet nuget push YuKitsune.Configuration.Env/bin/Release/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
      with:
          PROJECT_FILE_PATH: YuKitsune.Configuration.Env/YuKitsune.Configuration.Env/YuKitsune.Configuration.Env.csproj
